name: Prune unused files

on:
  workflow_dispatch:

jobs:
  prune:
    runs-on: ubuntu-latest
    concurrency:
      group: prune-oss-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Build Dist
        run: pnpm run build

      - name: Remove files
        run: pnpm run prune
        env:
          REGION: ${{ secrets.OSS_REGION }}
          ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          BUCKET: ${{ secrets.OSS_BUCKET }}
          REMOTE_PATH: ${{ secrets.OSS_REMOTE_PATH }}
