name: Upload dist

on:
  push:
    branches:
      - main
    paths:
      - "src/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    concurrency:
      group: upload-dist-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Setup OSS
        uses: ./.github/actions/setup-oss
        with:
          ossutil-config: ${{ secrets.OSSUTIL_CONFIG }}

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Build Dist
        run: pnpm run build

      - name: Upload to OSS
        run: ossutil64 cp -f -c ./.ossutilconfig -r dist/ ${{ secrets.OSS_REMOTE_PATH }}

      - name: Update PRTS Website
        run: pnpm run update ${{ secrets.PRTS_USERNAME }} ${{ secrets.PRTS_PASSWORD }}
