name: Upload dist

on:
  push:
    branches:
      - main

concurrency:
  group: upload-dist-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Build Dist
        run: pnpm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist
          if-no-files-found: error
          retention-days: 7

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Download dist artifact
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist

      - name: Upload to OSS
        run: pnpm run upload
        env:
          REGION: ${{ secrets.OSS_REGION }}
          ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          BUCKET: ${{ secrets.OSS_BUCKET }}
          REMOTE_PATH: ${{ secrets.OSS_REMOTE_PATH }}

  deploy:
    needs: upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Download dist artifact
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist

      - name: Update PRTS Website
        run: pnpm run update ${{ secrets.PRTS_USERNAME }} ${{ secrets.PRTS_PASSWORD }}
