name: Upload dist

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    concurrency:
      group: upload-dist-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Build Dist
        run: pnpm run build

      - name: Upload to OSS
        run: pnpm run upload
        env:
          REGION: ${{ secrets.OSS_REGION }}
          ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          BUCKET: ${{ secrets.OSS_BUCKET }}
          REMOTE_PATH: ${{ secrets.OSS_REMOTE_PATH }}

      - name: Update PRTS Website
        run: pnpm run update ${{ secrets.PRTS_USERNAME }} ${{ secrets.PRTS_PASSWORD }}
